### ISSUE TITLE
Webアプリケーションサーバの作成課題 - その1 Webアプリケーションプロジェクトの作成

### ISSUE THREAD

**Issue by stone-shun-oyama** [takkun1937/Java_CardGame#9]
## 内容

[SpringFrameWork](https://spring.io/)を利用したWebアプリケーションサーバの作成を行ってください。
※ この課題を行う前に、[Docker](https://www.docker.com/)のインストールを行ってください。

手順は以下のとおりです。
1. [Spring Initializr]()を使用してSpringアプリケーションのプロジェクトを作成する。
    - 以下の画像と同じ設定値で作成してください。
       ![スクリーンショット 2023-03-15 14 31 19](https://user-images.githubusercontent.com/35253763/225488739-d9b85bef-db45-487a-8eea-97b9200e37b1.png)

2. Webアプリケーションプロジェクトのディレクトリ直下に、以下の内容で「Dockerfile」及び「docker-compose.yml」を作成する。
    - Dockerfile
        ```Dockerfile
        FROM openjdk:17.0.2-slim-bullseye

        # Create user
        RUN groupadd -r normal_users && \
            useradd -r -g normal_users stone

        # Install common tools
        RUN apt update && \
            apt -y -qq install curl unzip
        ```
    - docker-compose.yml
         ```yml
         version: "3.9"
         services:
           card_game_server:
             build:
               context: .
               dockerfile: ./Dockerfile
             entrypoint: "bash -c '/home/stone/CardGameServer/gradlew bootRun'"
             container_name: card_game_server
             ports: 
               - 8080:8080
             tty: true
             user: stone
             volumes:
               - .:/home/stone/CardGameServer
             working_dir: /home/stone/CardGameServer
        ```
3. Webアプリケーションプロジェクトのディレクトリ内の`/src/main/resources/static/`配下に作成済みのトランプゲームWebアプリケーションを配置する。
    - 配置する際、WebアプリケーションのエンドポイントとなるHTMLファイルを「index.html」としてください。

4. Webアプリケーションプロジェクトのディレクトリ内に存在する「build.gradle」の`dependencies`を以下の様に書き換える。
  ```gradle
  dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-web'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
  }
  ```

5. Shell上でWebアプリケーションプロジェクト直下に移動し、以下のコマンドを実行してサーバを起動する。
    - `$ docker compose up -d`

6.  ブラウザのアドレスバーに「http://localhost:8080」にアクセスし、トランプゲームWebアプリケーションが表示されることを確認する。

7. トランプゲームWebアプリケーションが表示されることが確認できたら、新しいブランチを作成し、Webアプリケーションプロジェクトを本リポジトリのルートに配置してコミットする。

## 補足事項

- Webアプリケーションプロジェクトや配置したトランプゲームWebアプリケーションに何かしらの変更を加えた場合、その変更を反映してブラウザ上で表示するためには、サーバの再起動を行う必要があります。サーバの再起動を行うためには、Webアプリケーションプロジェクトのディレクトリ直下で以下のコマンドを実行してください。
    - `$ docker compose restart`

## 参考

- [Spring - Guides - Serving Web Content with Spring MVC](https://spring.io/guides/gs/serving-web-content/)
